from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle
)
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib import colors
from reportlab.lib.units import inch
from datetime import datetime


def generate_report(data):

    os.makedirs("outputs", exist_ok=True)

    filename = "outputs/SafeScrollAI_Report.pdf"

    doc = SimpleDocTemplate(filename)

    styles = getSampleStyleSheet()

    story = []

    title = Paragraph(
        "<font size=22><b>🛡 SafeScrollAI</b></font>",
        styles["Title"]
    )

    subtitle = Paragraph(
        "<font size=14>Intelligent Video Content Analysis Report</font>",
        styles["Heading2"]
    )

    story.append(title)
    story.append(subtitle)
    story.append(Spacer(1, 0.3 * inch))

    now = datetime.now()

    story.append(
        Paragraph(
            f"<b>Date:</b> {now.strftime('%d-%m-%Y')}",
            styles["Normal"]
        )
    )

    story.append(
        Paragraph(
            f"<b>Time:</b> {now.strftime('%H:%M:%S')}",
            styles["Normal"]
        )
    )

    story.append(Spacer(1, 0.2 * inch))

    table_data = [

        ["Video", data["Video"]],

        ["Duration", data["Duration"]],

        ["Resolution", data["Resolution"]],

        ["Frames Analysed", str(data["Frames"])],

        ["Prediction", data["Result"]],

        ["Confidence", data["Confidence"]],

        ["Risk Level", data["Risk Level"]],

        ["Processing Time", data["Processing Time"]]

    ]

    table = Table(table_data, colWidths=[2.2 * inch, 3.8 * inch])

    table.setStyle(

        TableStyle([

            ("BACKGROUND", (0, 0), (-1, 0), colors.darkblue),

            ("GRID", (0, 0), (-1, -1), 1, colors.grey),

            ("BACKGROUND", (0, 0), (0, -1), colors.lightgrey),

            ("FONTNAME", (0, 0), (-1, -1), "Helvetica"),

            ("BOTTOMPADDING", (0, 0), (-1, -1), 8),

            ("TOPPADDING", (0, 0), (-1, -1), 8),

        ])

    )

    story.append(table)

    story.append(Spacer(1, 0.35 * inch))

    story.append(

        Paragraph(

            "<b>AI Recommendation</b>",

            styles["Heading2"]

        )

    )

    risk = data["Risk Level"]

    if risk == "High":

        rec = """
• High probability of violent content.<br/>
• Manual moderation recommended.<br/>
• Apply viewer discretion warning.<br/>
• Restrict public visibility if necessary.
"""

    elif risk == "Medium":

        rec = """
• Possible violent activity detected.<br/>
• Human review is recommended.<br/>
• Verify content before publishing.
"""

    else:

        rec = """
• No significant violent content detected.<br/>
• Safe for general viewing.<br/>
• No moderation required.
"""

    story.append(

        Paragraph(

            rec,

            styles["BodyText"]

        )

    )

    story.append(Spacer(1, 0.3 * inch))

    story.append(

        Paragraph(

            "<b>Generated by SafeScrollAI</b>",

            styles["Heading3"]

        )

    )

    doc.build(story)

    return filename